canonical/istio-operators

charms/istio-ingressgateway/metadata.yaml
charms/istio-pilot/metadata.yaml

So that people don't accidentally use the current stable version

Add min-juju-version to charm metadata

---

charms/istio-pilot/reactive/charm.py

This avoids injecting sidecars into things that don't really need them

Switch to whitelist for sidecar injections

---

.github/workflows/test-microk8s.yaml

- Sets up `kubectl` correctly, so switch away from `sudo microk8s.kubectl`
- Lets us also drop `sudo juju`

Switch to balchua/microk8s-actions in CI

---

.github/workflows/publish.yaml

With the switch to the operator framework, the publishing job needs to have charmcraft installed.

Install charmcraft in publish workflow

---

.github/workflows/integration.yaml
.gitignore
charms/istio-ingressgateway/metadata.yaml
charms/istio-ingressgateway/requirements.txt
charms/istio-ingressgateway/src/charm.py
charms/istio-ingressgateway/test/unit/test_charm.py
charms/istio-pilot/metadata.yaml
charms/istio-pilot/requirements.txt
charms/istio-pilot/src/charm.py
charms/istio-pilot/test/unit/test_charm.py
tox.ini

Splits up service-mesh interface into ingress and ingress-auth interfaces, and uses the `schema` property for them. Punts on defining a full service-mesh interface until actually necessary to create.

Split up service-mesh interface

---

charms/istio-ingressgateway/src/charm.py
charms/istio-pilot/src/charm.py

Prevents a charm from getting stuck in WaitingStatus

Set ActiveStatus by default after version checking

---

.github/workflows/integration.yaml
charms/istio-ingressgateway/test-requirements.txt
charms/istio-ingressgateway/tox.ini
charms/istio-pilot/test-requirements.txt
charms/istio-pilot/tox.ini
tox.ini

Running `tox` from the top-level now runs tox tests in each charm's directory, instead of a user having to cd to each subdir and run them individually.

Rejigger how tox works

---

.github/workflows/publish.yaml

Using [upload action](https://github.com/canonical/charmhub-upload-action) for publish job.

.github/workflows/publish.yaml: updates job with charmhub upload action

---

.github/workflows/publish.yaml

Fix charm paths in publihs action which were overlooked in the code
review of the previous PR.

Fix charm paths in publish action

---

.github/workflows/publish.yaml
charms/istio-gateway/metadata.yaml
charms/istio-pilot/metadata.yaml

This PR introduces the following:
* charms/*/metadata.yaml: specifies image latest tag 
* .github/workflows/publish.yaml: fix matrix syntax

.github/workflows/publish.yaml: fix matrix syntax

---

charms/istio-ingressgateway/metadata.yaml

The charm for `istio-ingressgateway` in the main track was renamed `istio-gateway`.  This commit backports that change to the track/1.5 branch to ensure the old version publishes to the same charm.
This should not be merged until [this track creation request](https://portal.support.canonical.com/staff/s/case/5004K00000E7IgaQAF/create-tracks-in-charmhub-for-kubeflow-team) is completed.

change track/1.5 istio-ingressgateway charm name

---

.github/workflows/integration.yaml
charms/istio-pilot/requirements.txt

Pin Jinja dependency markupsafe to v2.0.1
This issue is caused by a change in Jinja's dependencies.  This is a workaround that forces an older version of markupsafe for the time being.
https://github.com/pallets/jinja/issues/1585

Pin markupsafe==2.0.1 for Jinja bug workaround

---

charms/istio-gateway/metadata.yaml
charms/istio-gateway/tests/unit/conftest.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/metadata.yaml
charms/istio-pilot/tests/unit/test_charm.py
tests/test_bundle.py

This PR introduces the following:
* charms/*/metadata.yaml: replaces oci-image with noop
* tests/test_bundle.py: replaces build_bundle with explicit & individual methods
juju-bundle is not as transparent as using individual commands, and since this is a test, we can afford the extra steps, so we can be more explicit on what we are executing and what part is causing issues in case of a failure.
Depends on #63

Improves bundle testing and removes oci-image resource

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/src/resources_handler.py
charms/istio-pilot/tests/unit/conftest.py
charms/istio-pilot/tests/unit/test_charm.py

This PR introduces the following changes:
* istio-pilot/src: extracts all lightkube logic to a helper module
* istio-pilot/tests/unit: skipping all tests as they need to be refactored
> Note: unit tests will be changed in a follow up PR

Refactors charm.py extracting all lightkube logic to a helper module

---

charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml
tests/test_bundle.py

If istio-gateway was deployed as kind=ingress with application name istio-ingressgateway, a service in manifest.yaml had a name collision with the juju-created istio-ingressgateway service.  This is fixed by adding suffixes on the resource names.
All credits to @ca-scribner

fix: naming of istio-ingressgateway service

---

charms/istio-pilot/tests/unit/conftest.py
charms/istio-pilot/tests/unit/test_charm.py

The way Client.list is mocked in conftest.py does not apply to all test cases as it is directly building the resource's metadata and other parameters, which might not be useful for tests where the resources metadata is provided by the test case itself. Extracting this mock and leaving it inside test_charm.py prevents other test modules to use it as a fixture.
Blocks unit tests in #69

istio-pilot: moves mocked_list out of conftest.py

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/src/resources_handler.py
charms/istio-pilot/tests/unit/test_resources_handler.py

istio-pilot/src/resource_handler.py: implements a reconcile resources method
In previous versions of this file we are removing all resources of
a kind and then applying them again w/o caring about their origin.
This could raise issues if any related charm is using such resource at the moment
of removal.
Using a reconcile helper method allows us to keep alive the existing
resources and only remove those that are not backed by a relation.
In this commit this method is implemented and also used for the
handle_ingress event handler as a fix for #50.
Fixes #50
This PR also adds unit tests for the reconcile method, but those depend on #74

Implements reconcile resources method

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/src/resources_handler.py
charms/istio-pilot/tests/unit/test_charm.py
charms/istio-pilot/tests/unit/test_resources_handler.py

In order to keep naming consistent across the charm code and [Lightkube](https://github.com/gtsystem/lightkube), we have decided to use the word "resources" instead of "object" in any method or var that handles Kubernetes resources.
These changes affect the charm code and the tests.

Replaces "object" with "resource" to keep standard

---

.github/workflows/publish.yaml
.github/workflows/release.yaml

Add new release charm action. Update publish action to use `upload-charm` as the release action need the release info from that action. 
It's using the release charm action from [promote-charm branch](https://github.com/canonical/charming-actions/tree/promote-charm). This would be updated in the future to use stable version

test release charm action

---

.github/workflows/release.yaml

Release action fails because it can't find `metadata.yaml` file in the directory. 
Provide charm-path to release action. Use tag-prefix as input as it is the same as the directory names. This way users have one less field to fill

add charm path release action

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

To reflect recent changes, we need to change how existing resources are removed.
Depends on #84

Series of fixes to remove event handler

---

charms/istio-gateway/metadata.yaml
charms/istio-pilot/metadata.yaml

`min-juju-version` is deprecated, `assumes` should be used now.

Replaces min-juju-version with assumes

---

charms/istio-pilot/src/charm.py
tests/test_bundle.py

This PR slightly refactors the way we retrieve and check the ingressgateway address. First of all, since we recently changed the `Service` name in [this](https://github.com/canonical/istio-operators/commit/de0a9487fc7facf52567c7db93cdbf4433bcfc1d) commit, we have to reflect those changes on istio-pilot's code. Secondly, when we have a try/catch block that defers the event if there is not an ingressgateway address, but we were not setting the unit status and giving the correct messaging; the status was set to `Active` regardless.

Small refactor on handle_ingress and _gateway_address

---

.github/workflows/integration.yaml
charms/istio-gateway/charmcraft.yaml
charms/istio-gateway/requirements.txt
charms/istio-gateway/src/charm.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/charmcraft.yaml
charms/istio-pilot/src/charm.py
test-requirements.txt

`istio-gateway` has a strong dependency on `istio-pilot`'s relation data to actually create the k8s resources both of the charms need. This PR introduces changes that will ensure the data is sent, as well as the correct messaging and status is shown.

Fixes for missing svc/istio-ingressgateway-workload

---

.github/workflows/integration.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml

Charming actions updated according to the ones agreed on template-operator charm.
The aim was to:
- update release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a multiple-charm repo with no resources.

Update charming actions

---

charms/istio-pilot/requirements.txt
charms/istio-pilot/src/resources_handler.py
charms/istio-pilot/tests/unit/test_charm.py
charms/istio-pilot/tests/unit/test_resources_handler.py
test-requirements.txt

This PR introduces the following:
* refactor: use load_all_yaml with create_resources_for_crds as True
Due to [recent changes](https://github.com/gtsystem/lightkube/pull/34/commits/4446c4093698637d646b57e37a021abe9da1ef6d) in the Lightkube API, in particular the branch we are using temporarily, we have to use load_all_yaml instead of from_dict to obtain the class of custom generic resources.
* fix: remove incorrect argument from codecs.from_dict()
Lightkube's [`codecs.from_dict()`](https://github.com/gtsystem/lightkube/blob/master/lightkube/codecs.py#L43) does not accept the client arg. This commit removes it to avoid this error:
```
2022-07-07 19:44:10,396 ERROR    Uncaught exception while in charm code:
Traceback (most recent call last):
File "./src/charm.py", line 334, in <module> …
```

fix: remove incorrect argument from codecs.from_dict()

---

charms/istio-pilot/src/charm.py

The previous implementation logged all exceptions, which made logs very noisy and led to confusion. Changing that to use log.debug when the exception is of TypeError or ApiError, and use log.error when an unexpected error is caught. This commit also changes the event.defer() call so that it only happens on expected errors.

refactor: use log.debug and log.error on certain exceptions in istio-pilot charm code

---

charms/istio-pilot/config.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/src/gateway-secret.yaml.j2
charms/istio-pilot/src/gateway.yaml.j2
charms/istio-pilot/tox.ini

"Add ssl-* configs to pass cert and key. That should be
used to create a secret and added to the gateway yaml.
Added --diff to lint to show more details on tox.ini." - From #88 
This is a clone PR that will take care of rebases and code changes (if any) while @phvalguima is OOO.

Add SSL support (clone #88)

---

charms/istio-pilot/lib/charms/istio_pilot/v0/istio_gateway_name.py

To comply with charmcraft library requirements and publish it to charmhub, `LIBID` had to be added to `istio_gateway_name.py`.

Add LIBID to published library

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

The handle_default_gateway method is not run on config_changed at deployment time,
this is an unexpected behaviour that happens when istio-pilot is related to
multiple other charms in a bundle. Although config_changed is guaranteed to
run after install, that is not the case under the described conditions, causing
the default gateway to not be created without human intervention.
To avoid this situation, and given that istio-pilot is usually deployed in a bundle
and related to multiple charms, the handle_default_gateway method can be also bound to
["ingress"].relation_created, which is also guaranteed to run after install.
Fixes: canonical/istio-operators#94

fix: bind handle_default_gateway to ingress_relation_created

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This PR introduces the following changes:
* fix: add a check for gateway relation to avoid sending data when units haven't joined  
* fix: bind handle_gateway_relation to update_status and handle_gateway_relation
When deployed in a bundle with a large number of charms,
it seems like the istio-pilot charm cannot handle all the
relations correctly at the same time. Binding handle_gateway_relation
to update_status ensures that at least gateway_data is sent eventually.

 Temporal fixes for sending gateway information through relations

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

Cherry-pick commits from `main` introduced by #111 to `track/1.11`

[cherry-pick] Temporal fixes for sending gateway information through relations

---

charms/istio-pilot/lib/charms/istio_pilot/v0/istio_gateway_info.py
charms/istio-pilot/metadata.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/src/istio_gateway_info_provider.py
charms/istio-pilot/tests/unit/test_charm.py

The relation and interface name `gateway`  and `istio-gateway-name` are very ambiguous and generic, and could lead to confusion.
This PR renames all instances of gateway and istio-gateway-name, including those in the lib. Please NOTE following this PR we MUST update the lib in Charmhub with `charmcraft push-lib` after this PR is merged.
Blocks: [PR#27](https://github.com/canonical/kubeflow-tensorboards-operator/pull/27), [PR#486](https://github.com/canonical/bundle-kubeflow/pull/486)

refactor: renames gateway relation and gateway-name interface

---

.github/workflows/integrate.yaml
charms/istio-pilot/src/auth_filter.yaml.j2
charms/istio-pilot/src/charm.py
charms/istio-pilot/src/gateway.yaml.j2
charms/istio-pilot/tests/unit/test_charm.py
test-requirements.txt
tests/test_bundle.py
tests/test_ingress_auth_manifest_for_setup.yaml.j2

This change restricts the `EnvoyFilter` created by the `ingress-auth` relation to apply only to the port (8080) which is used for Kubeflow's ingress traffic through the ingress gateway.  This is to address problems like seen in canonical/knative-operators#51, where our previous configuration accidentally forwarded in-cluster traffic to dex.
* clone this repo
* `KUBECONFIG=[path-to-your-kubeconfig] tox -e integration
Fixes canonical/knative-operators#51

Update `ingress-auth` relation to only restrict traffic on the Kubeflow ingress

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/conftest.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This is PR based on: 
- https://github.com/canonical/istio-operators/pull/67
- https://github.com/canonical/istio-operators/pull/129
This PR allows exposing applications behind the Istio gateway via Ingress Controller & rule

Added ingress service type variable (ClusterIP or Loadbalancer)

---

charms/istio-pilot/src/prometheus_alert_rules/istio.rule
tests/test_cos_integration.py

Adds alert rules and corresponding unit/integration tests.
Dear reviewers, this PR depends on #132, and thus should be merged after rebasing on top of a HEAD with the change from that other PR.

feat: add alert rules for istio-pilot

---

charms/istio-pilot/charmcraft.yaml

Bump the version of the binary we use in istio-pilot.
* juju deploy local build goes active and idle
* deploy local build of `istio-pilot` alongside the [Charmed Kubeflow 1.6 bundle](https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.6/stable/kubeflow/bundle.yaml), all charms that relate to istio-pilot are active and idle
* after proper configuration, the Kubeflow Dashboard (from provided by the bundle ^) can be accessed

feat: istioctl version bump 1.11->1.16

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
charms/istio-gateway/requirements.txt

This PR introduces the following:
* ci: pin ubuntu 20.04 in integrate, publish, and release jobs
Pinning the version avoids incompatibilities with building the charm and installing certain dependencies.
* build: pin lightkube and lightkube-models to versions that are compatible with the charm and test code
* bootstrap juju with agent 2.9.34 to avoid https://bugs.launchpad.net/juju/+bug/1992833

ci: multiple fixes for track/1.11 CI

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/conftest.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This is a backport from main to track/1.11 of the following:
* [Added change to istio-pilot to change ingress workload as ClusterIP](https://github.com/canonical/istio-operators/commit/7943735b67a56df05ae58d1d3c162b94347ab5fa)
* [code review comments applied.](https://github.com/canonical/istio-operators/commit/afb2a50c4a917b8dc758248505478eed12f6a840)
* [missing type key added](https://github.com/canonical/istio-operators/commit/9947502f59ae700940db9335aaa38a70edcdeb19)
* [Added ingress service type variable with options ClusterIP and Loadba…](https://github.com/canonical/istio-operators/commit/9c11f131ef110080569ebcb6c6120ccb4924c78e)

backport config option to enable ClusterIP usage

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/tests/unit/conftest.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

#175 and elsewhere requests that the `istio-gateway` charm allow for access through a `NodePort` rather than just through a `LoadBalancer` or `ClusterIP`.  This feature is implemented here, where add another valid entry for `gateway_service_type`, `gateway_service_type=NodePort`
Because of how `istio-pilot` was using the service provided by `istio-gateway`, we also need to change some of the logic around how `istio-pilot` interrogates the gateway it finds.  Included here too are these changes, as well as an expanded test suite.
See #175 for more context.  closes #175
Note that these instructions use charmhub `edge/branch` charms.  If you don't have access to the charmhub branch charms, you must build istio-pilot and istio-gateway for yourself locally.
(edited Feb 22 to fix the auth …

feat: add option to use `NodePort` for istio-gateway

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/tests/unit/conftest.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py
test-requirements.txt

This is a backport of the NodePort feature implemented in the main branch for PR #176.  This attempts to extract any non-relevant features from that branch, importing only those needed to support NodePort gateways.  See #176 for more details on functionality.
(cherry picked from commit 0dd331421462a539b427fbd95d1bdb91d57311ce, but with some modifications)

feat: Backport `NodePort` to track 1.11

---

.github/workflows/integrate.yaml
tests/test_bundle.py
tests/test_cos_integration.py

The bug[1] in juju that was forcing us to pin the agent to version 2.9.34 is fixed now in 2.9.42. This commit bumps the agent version and adds the "series" field in deploy statements in tests so we can use the new juju agent version.
[1] https://bugs.launchpad.net/juju/+bug/1992833
* ci: bump juju agent 2.9.34 -> 2.9.42
* tests: add series=focal when deploying istio

ci: bump juju agent 2.9.34 -> 2.9.42 (#200)

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This extends the patch for #204 to fix install events.  Prior to this patch, istioctl for v1.12-1.14 creates a ValidatingWebhookConfiguration that points to istiod in the istio-system namespace rather than the namespace where istiod is deployed.

fix: patches misconfigured ValidatingWebhook on Install

---

charms/istio-pilot/config.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This is based on #234.  Recommended that this be reviewed after #234 is merged as that accounts for most of the changes.  This is part of a larger effort to refactor istio-pilot's event handling, as described [in jira](https://warthogs.atlassian.net/browse/KF-728). This merges into a feature branch and covers only part of the total effort.
Includes:
* helpers that check on istio-gateway's service
* tests for helpers
* added a config option for the istio-gateway's service name to make things easier to test and deploy

add istio-gateway helpers to istio-pilot event handler rewrite

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/src/manifests/auth_filter.yaml.j2
charms/istio-pilot/tests/unit/test_charm.py

This is based on #235.  Recommended that this be reviewed after #235 is merged as that accounts for some of the deltas.  This is part of a larger effort to refactor istio-pilot's event handling, as described [in jira](https://warthogs.atlassian.net/browse/KF-728). This merges into a feature branch and covers only part of the total effort.
Includes:
* _reconcile_ingress_auth
* related ingress-auth helpers
* tests

add istio-pilot ingress-auth reconciler to event handler rewrite

---

charms/istio-pilot/lib/charms/istio_pilot/v0/istio_gateway_info.py
charms/istio-pilot/tests/unit/test_gateway_info.py

This library can be used by other charms that can provide gateway information. The previous implementation of the library did not include the provider logic. This commit extends the API to be able to instantiate the provider class in other charms other than istio-pilot.
TODO:

refactor: include provider class in gateway-info library

---

charms/istio-pilot/requirements-unit.txt
charms/istio-pilot/requirements.in
charms/istio-pilot/requirements.txt
charms/istio-pilot/src/charm.py
charms/istio-pilot/src/manifests/gateway.yaml.j2
charms/istio-pilot/tests/unit/test_charm.py

Adds:
* _reconcile_gateway
* _remove_gateway
* helpers to support these
* unit tests to test everything added
Note that this temporarily uses a version of charmed-kubeflow-chisme pulled from a specific commit in github.  This is required to enable KubernetesResourceHandler.reconcile() and .delete() features.  This will be removed when the updated KRH is approved and merged.

feat: add Gateway reconciliation/removal features

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/src/manifests/virtual_service.yaml.j2
charms/istio-pilot/tests/unit/test_charm.py

This is based on #243. Recommended that this be reviewed after #243 is merged as that accounts for some of the deltas. This is part of a larger effort to refactor istio-pilot's event handling, as described [in jira](https://warthogs.atlassian.net/browse/KF-728). This merges into a feature branch and covers only part of the total effort.
* adds _get_ingress_data() to pulls route data from ingress relations
* adds _reconcile_ingress() to update, modify, and delete ingresses based on the related applications
* refactors the virtual_service.yaml.j2
* refactors gateway name/namespace handling into properties to make it shared between gateway and ingress handling
* adds unit tests for above new functions

feat: add ingress relation handler to istio-pilot event handling refactor

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This is based on #247. Recommended that this be reviewed after #247 is merged as that accounts for some of the deltas. This is part of a larger effort to refactor istio-pilot's event handling, as described [in jira](https://warthogs.atlassian.net/browse/KF-728). This merges into a feature branch and covers only part of the total effort.
Adds handler for istio-pilot's istio-pilot relation, plus tests.

feat: add handler for istio-pilot's istio-pilot relation

---

charms/istio-pilot/lib/charms/istio_pilot/v0/istio_gateway_info.py
charms/istio-pilot/tests/unit/test_gateway_info.py

This PR:
* removes the check in Provider.send_gateway_relation_data that asserted we needed at least one related app
* adds a gateway_up field to the data bag, defaulting to True if it is absent (to ensure backward compatibility and allow this Requirer to relate to older Providers

feat: update gateway-info lib

---

charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml

change API version.
safe change since this is supported in K8s since 1.21
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
once updated on local charm within a bundle the resource can be successfully applied

KF-3009 update k8s api version

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/src/manifests/auth_filter.yaml.j2
charms/istio-pilot/tests/unit/test_charm.py

This PR updates the EnvoyFilter definition to always apply auth to both http and https traffic, regardless of which is currently enabled in the Gateway.  This is to prevent the possibility of these objects going out of sync (eg: Gateway allowing traffic on one port, and EnvoyFilter applying Auth on traffic through the other port), which could have occurred if the charm succeeded in updating one of those objects but failed to update the other (due to an error or incompatible settings).  By always applying the EnvoyFilter to all traffic, this possibility is prevented.
This PR came from an attempt to address https://github.com/canonical/bundle-kubeflow/issues/570, which showed our previously was misconfiguring the `EnvoyFilter` when using SSL.  It was reported that we incorrectly applied the …

Fix handling of SSL

---

charms/istio-pilot/src/charm.py

To keep some backwards compatibility with istio-pilot 1.16/stable rev413, we need to set back the `field_manager` vairable from `istio-pilot` (introduced by [df2e23b](https://github.com/canonical/istio-operators/blob/track/1.16/charms/istio-pilot/src/charm.py#L93)) to `lightkube`, as it was in the mentioned revision (see [state of charm](https://github.com/canonical/istio-operators/blame/fbacbd67d829df7113d90adc3a30559f7a7e0aa9/charms/istio-pilot/src/charm.py#L74) ~5 months ago); otherwise we'll get conflicts with certain patched/applied Kubernetes resources when refreshing from 1.16/stable rev413 to 1.16/edge rev 542 and higher.
[Error logs](https://pastebin.canonical.com/p/gqwgKkSBrZ/)

fix: set field_manager to lightkube instead of istio-pilot

---

tools/get-images-1.7-stable.sh

Repository specific list of images.
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup.
Summary of changes:
- Added script that retrieves image managed by charm(s).

feat: get images for istio

---

charms/istio-gateway/tox.ini
charms/istio-pilot/tox.ini
tox.ini

Updates tox.ini's `update-requirements` as described in https://github.com/canonical/argo-operators/pull/100

update tox.ini's update-requirements

---

charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml
charms/istio-pilot/charmcraft.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/src/manifests/gateway.yaml.j2
charms/istio-pilot/tests/unit/test_charm.py

This PR introduces the following changes:
* Bump the istioctl binary 1.16 -> 1.17
* Bump the API version of Gateway `v1beta1` -> `v1alpha3`
* Bump the docker.io/istio/proxyv2 image tag from 1.16 -> 1.17.3
* Delete the `PodDisruptionBudget` from the cluster due to https://github.com/istio/istio/issues/12602 and https://github.com/istio/istio/issues/24000
* Set the following to
```
preferredDuringSchedulingIgnoredDuringExecution: null
requiredDuringSchedulingIgnoredDuringExecution: null
```
in the `Gateway` deployment according to https://github.com/kubeflow/manifests/pull/2426
All these updates were made using https://github.com/kubeflow/manifests/pull/2483 as reference.
> NOTE: The changes in this PR may require microk8s > 1.24/stable, the CI may need #310 to be merged before it goes …

feat: bump istio-operators 1.16->1.17

---

tests/test_bundle.py

We used to workaround juju/python-libjuju#900 by addind long waits and asserting the presence of certain resources before continuing with the test exectuion. Since the issue is not resolved, we don't need to do this workaround anymore. Fixes #303

tests: remove wait for idle woraround as juju/python-libjuju#900 is fixed

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

Istio 1.12-1.14 had an issue with the ValidatingWebhookConfiguration and the namespace, which we patched in the charm code to prevent errros. Since this issue is not present in recent versions of the charm, we do not need the workaround anymore. This code is still valid in previous versions and can be left in those branches.

chore: remove patches for istio < 1.16

---

charms/istio-gateway/charmcraft.yaml
charms/istio-pilot/charmcraft.yaml

This pin is not needed anymore, and in fact we want the latest versions of setuptools and pip.

build: unpin setuptools and pip in charmcraft.yaml as pypa/setuptools_scm#713 is fixed

---

.github/workflows/integrate.yaml

Using a matrix to test the istio-operators in the two supported versions of microk8s (1.25 and 1.26). Also installing the strict version of microk8s in preparation for juju 3.1 usage.

ci: use matrix strategy to test on different microk8s versions

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

While handling relation-broken events for ingress, we see either:
* event.app=the_departing_app
* event.app=None
The previous charm logic did not cover the second case, leading to an uncaught KeyError.
We aren't sure what controls which of the situations we encounter, but we add error handling here to at least log the event and avoid uncaught exceptions.
Fixes https://github.com/canonical/istio-operators/issues/189
Part of #292

fix: handle ingress `relation-broken` when `event.app==None`

---

.github/workflows/integrate.yaml
charms/istio-pilot/src/charm.py

Fixes #325 
* istioctl install in any model namespace not kubeflow
* ci: test in non-kubeflow namespace

fix: `istioctl install` and test in non-kubeflow namespace

---

tests/test_cos_integration.py

Prometheus updates on `latest/edge` require Juju > 3.0.3. Temporary pin to the revisions that will allow integration tests to deploy those charms.
More details are in:
- https://github.com/canonical/bundle-kubeflow/issues/688
- Pinned revisions of prometheus to avoid failure of integration tests. Refer to above issue for more details.

fix: pin prometheus to specific revision

---

.github/workflows/integrate.yaml

As canonical/charmcraft#1132 got fixed, destructive mode can now be removed from the tox command when running integration tests. The fix is in latest/edge, this commit also points to that version.
minor nit: fix the path of charmcraft logs for collecting them.
Fixes: #340

ci: run integration tests w/o destructive mode

---

.github/workflows/integrate.yaml
charms/istio-pilot/charmcraft.yaml
charms/istio-pilot/config.yaml
charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
charms/istio-pilot/lib/charms/tls_certificates_interface/v2/tls_certificates.py
charms/istio-pilot/metadata.yaml
charms/istio-pilot/requirements-unit.in
charms/istio-pilot/requirements-unit.txt
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py
tests/test_bundle.py
tests/test_bundle_tls.py
tox.ini

Enabling the certificates relation enables the integration with tls-certificates-operator and other charms that provide CA certificates. These CA certificates are used by istio-pilot to configure TLS on the ingress Gateway resource.
In the past this was done exclusively via charm configuration, which is now removed in favour of CA certificates provided through the certificates relation.
1. Deploy the following:
```bash
juju deploy istio-gateway istio-ingressgateway --trust --config kind=ingress --channel latest/edge
juju deploy self-signed-certificates --channel edge
```
2. In parallel, build `istio-pilot` from this PR's branch
3. Deploy `istio-pilot` and relate
```bash
juju deploy ./istio-pilot*.charm --trust
juju relate istio-pilot istio-ingressgateway
juju relate …
```

feat: enable certificates relation on istio-pilot

---

charms/istio-pilot/README.md

Adds instructions for enabling TLS ingress gateway on the istio control plane using a TLS certificates provider.
Merge after #338

docs: add TLS certificates integration instructions

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

Put istio-pilot into waitingStatus until the ingress-auth data provider changes the data in the relation data bag.
Fixes #336 
Fixes #346

fix: set charm to waitingStatus if missing ingress auth data

---

.github/workflows/integrate.yaml

Use the latest candidate version of charmcraft to avoid potential issues with the edge version of charmcraft.
This commit is specifically reacting to canonical/craft-application#167
> NOTE: this change makes sure that the repository is aligned with our other repositories, most of them (with very few exceptions) point to latest/candidate.

ci: use charmcraft latest/candidate instead of latest/edge

---

charms/istio-pilot/config.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

feat: enable Istio CNI plugin by default
This commit enables the Istio CNI plugin by default in all new
deployments of istio-pilot provided the required charm configuration is
present; otherwise the control plane remains intact.
It is also ensured that the required configurations are present when
upgrading to future versions so the plugin is correctly installed on
existing control planes (versions <1.17).
Fixes #356
Part of #351
Env:
* microk8s 1.25-strict/stable
* microk8s enable dns hostpath-storage rbac metallb:10.64.140.43-10.64.140.49
* juju 3.1
* juju controller same version ^
<details>
<summary> Test charm installation </summary>
1. Set env variables
```
DEFAULT_GATEWAY="test-gateway"
KNATIVE_CHANNEL="latest/edge"
```
2. Build and deploy `istio-pilot` from this branch ` juju deploy …

feat: enable Istio CNI plugin by default

---

charms/istio-pilot/README.md

Adds instructions for enabling the Istio CNI plugin based on the implementation of #351.
Fixes #366

docs: add instructions to enable istio cni plugin

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

This setting allow users to access debug logs.
Fixes #370
As described in #370's description.

feat: set meshConfig.accessLogFile configuration for exposing logs

---

charms/istio-pilot/config.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py
tests/test_bundle.py

feat: enable csr-domain-name config option so istio-pilot can use it on CSRs
The istio-pilot charm already has a mechanism in place to discover the ingress gateway address from the `Service`, but it is limited to only returning IP addresses, which not all TLS certificate providers accept as a valid cert subject. Having the domain-name config option will allow users to specify the domain name they'd like to use when integrating with TLS certificate operators. This feature expands the support for integrating with TLS certificate providers that cannot issue signed certificates on a CSR that only contains an IP address (like we used to do).
This commit also adds some test coverage to test the recently added code.
Fixes #379

feat: add `csr-domain-name` config option 

---

tests/test_bundle.py

This charm has been refactored into a sidecar which now requires to be trusted, which makes the CI to fail because it cannot deploy this test dependency. On the other hand, the integration test execution should be kept exactly the same as when v1.17 of the istio-pilot was released, thus pinning the charm dependency is a way to keep things consistent and avoid issues.

tests: pin kubeflow-volumes to its 1.8/stable channel

---

charms/istio-pilot/metadata.yaml

In recent versions of charmcraft, the summary line must not exceed 78 characters. This change has been introduced in v2.5, which is heavily used by CKF charms. Since pinning the charmcraft version to an earlier release won't scale correctly, it has been decided to move on with the workaround, which aligns more to what charmcraft will expect in the future.
See canonical/charmcraft#1568 for reference.
We must ensure that changes in this metadata won't affect upgrades.
1. Deploy `istio-operators` charms from charmhub v1.17 and relate them
2. Refresh the `istio-pilot` to the version published by this PR
3. Check for errors
> NOTES: 
1. we must change this field in `main` and `track/1.17`
2. the CI will fail because of kubeflow-volumes, #388 fixes the issue

fix: shorten the summary as a workaround for canonical/charmcraft#1568

---

charms/istio-pilot/config.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

feat: enable csr-domain-name config option so istio-pilot can use it on CSRs
The istio-pilot charm already has a mechanism in place to discover the ingress gateway address from the `Service`, but it is limited to only returning IP addresses, which not all TLS certificate providers accept as a valid cert subject. Having the domain-name config option will allow users to specify the domain name they'd like to use when integrating with TLS certificate operators. This feature expands the support for integrating with TLS certificate providers that cannot issue signed certificates on a CSR that only contains an IP address (like we used to do). This commit also adds some test coverage to test the recently added code.
Fixes #379
NOTE: CI may fail because of #385 and #384 
Assuming you've got a …

feat: add `csr-domain-name` config option  (#381)

---

charms/istio-pilot/metadata.yaml

In recent versions of charmcraft, the summary line must not exceed 78 characters. This change has been introduced in v2.5, which is heavily used by CKF charms. Since pinning the charmcraft version to an earlier release won't scale correctly, it has been decided to move on with the workaround, which aligns more to what charmcraft will expect in the future.

fix: shorten the summary as a workaround for canonical/charmcraft#1568 (#389)

---

charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py

The _cni_config_changed() method was not called correctly because of a typo, which led to the condition evaluating it to always be True, and running upgrades when they are not required. Calling correctly the method ensures the charm executes correct pieces of code.
By doing this, the GenericCharmRuntimeError exception that gets raised on an error with CNI configuration must be re-raised when handling the reconcile.
Fixes #395

fix: call self._cni_config_changed and handle exception

---

.github/workflows/integrate.yaml
charms/istio-pilot/actions.yaml
charms/istio-pilot/src/charm.py
charms/istio-pilot/tests/unit/test_charm.py
tests/test_bundle_tls_provider.py
tests/test_bundle_tls_secret.py
tox.ini

* feat: add action to handle SSL values as secrets for TLS configuration
This commits introduces actions that allow users to configure the TLS ingress gateway for a single host directly passing the SSL cert and key to the charm.
- save-tls-secret: allows users to pass the ssl-key and ssl-crt values, which the charm saves in a juju secret (owned by the charm) and uses them to reconcile the ingress Gateway with such information.
- remove-tls-secret: a handy action that allows users to remove the TLS secret, which in turn removes the TLS configuration from the ingress Gateway.
This commit also adds unit and integration tests to increase the coverage due to the recent changes.
WARNING: please note this feature is only supported in 1.17 and 1.18, and it will be removed after releasing 1.18 in …

feat: add action to handle SSL values as secrets for TLS configuration (#394)

---

tests/test_bundle.py

The integration tests were deploying versions of dependency charms that do not correspond to the current release of the istio-operators. This commit brings all the correct versions and configure charms accordingly to ensure the integration tests execute in the same environment as this version of the istio-operators were design for.

tests: point all the integration charm deps to their 1.8 versions

---

tests/test_bundle.py
tests/test_bundle_tls_provider.py
tests/test_cos_integration.py

This commit pins all charms that get deployed from Charmhub to a compatible version to the CKF 1.8 release.
Part of canonical/bundle-kubeflow#863

tests: use stable versions of COS and TLS charms

---

charms/istio-pilot/src/charm.py

This commit ensures the istio-pilot charm checks that the ingress routes dictionary it uses for reconciling VirtualServices from requirers is not empty and the relation data for the departing application is there before attempting to pop values during a RelationBroken event.
Fixes #423
1. Follow the steps to reproduce in #423 to ensure the issue is happening
2. Remove the charm and re-deploy it from this PR
3. Try the steps in #423 again and make sure there is no error

fix: check routes before popping values

---

charms/istio-pilot/README.md

This commit adds a section in the README to document instructions for enabling the TLS ingress gateway using juju secrets.
Part of #398

docs: add instructions for TLS with secrets

---

charms/istio-gateway/config.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml
charms/istio-pilot/charmcraft.yaml
charms/istio-pilot/config.yaml
charms/istio-pilot/src/istioctl.py
charms/istio-pilot/tests/unit/test_charm.py
charms/istio-pilot/tests/unit/test_istioctl.py
tests/test_bundle.py

This commit adds support for istio operators 1.20.6.
Part of https://github.com/canonical/istio-operators/issues/413

feat: add support for istio 1.20.6

---

charms/istio-gateway/config.yaml
charms/istio-gateway/metadata.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml
charms/istio-pilot/charmcraft.yaml
charms/istio-pilot/config.yaml
charms/istio-pilot/metadata.yaml
charms/istio-pilot/src/istioctl.py
charms/istio-pilot/tests/unit/test_charm.py
charms/istio-pilot/tests/unit/test_istioctl.py
tests/test_bundle.py

This PR forward ports the following changes:
* feat: add support for istio 1.22.0 (#427)
* chore: use assumes juju 3.1 instead of 3.5 (#436)

feat, chore: add support for istio 1.22.0 and assume juju 3.1

---

charms/istio-gateway/metadata.yaml
charms/istio-pilot/metadata.yaml

We must ensure we do not break the deployment of existing users with a hard requirement on juju 3.5. Since in our documentation the least supported juju version is 3.1, we should reflect that also in these charms. The only scenario where people are required to bump juju to 3.4 or greater is when they want to set the TLS ingress gateway with secrets, but this is documented in a public guide.

chore: use assumes juju 3.1 instead of 3.5

---

tests/test_bundle.py

The integration tests were deploying versions of dependency charms that do not correspond to the current release of the istio-operators. This commit brings all the correct versions and configure charms accordingly to ensure the integration tests execute in the same environment as this version of the istio-operators were design for.

tests: point all the integration charm deps to their 1.7 versions

---

charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml

The default values of the nodeAffinity field were causing this charm to cause undesired behaviours when trying to replace them (either manually or via the namespace-node-affinity charm. This commit removes those defaults from istio-gateway 1.16, newer versions of this charm do not present this issue.
Fixes #426
1. [Create a microk8s cluster](https://microk8s.io/docs/clustering) (2 worker nodes, 1 admin node). You can do it with [LXD containers](https://microk8s.io/docs/install-lxd).
2. Label one of the nodes with an obvious label, it can be `kubectl label node workload=istio-deploys-here`
3. For testing purposes, the admin node will also have a juju controller bootstrapped inside, but this can be done using a controller bootstrapped elsewhere.
4. Add a model `istio-test` and label it with …

fix: remove default nodeAffinity configurations

---

.github/workflows/integrate.yaml

ci: bump microk8s 1.25(lower) and 1.29(upper)

---

.github/workflows/integrate.yaml

ci: bump microk8s 1.25(lower) and 1.28(upper)

---

.github/workflows/integrate.yaml

ci: bump microk8s 1.26(lower) and 1.29(upper)

---

.github/workflows/integrate.yaml

ci: bump microk8s 1.27(lower) and 1.30(upper)

---

.github/workflows/integrate.yaml

ci: bump microk8s 1.24(lower) and 1.27(upper)

---

.github/workflows/integrate.yaml

ci: use juju 3.4/stable instead of 3.5/stable in track 1.21

---

.github/workflows/integrate.yaml

ci: use juju 3.4/stable instead of 3.5/stable in track 1.19

---

.github/workflows/integrate.yaml

ci: use juju 3.4/stable instead of 3.5/stable in track 1.20

---

.github/workflows/integrate.yaml

ci: use juju 3.4/stable instead of 3.5/stable in track 1.17

---

.github/workflows/integrate.yaml

ci: use juju 3.4/stable instead of 3.5/stable in track 1.18

---

tests/test_bundle.py

The public-url configuration option has been replaced by a relation between dex-auth and oidc-gatekeeper. Because of that, configuring this option is not required anymore, and in fact if kept, can cause errors as it won't be recognised by Juju anymore. This commit removes the extra configuration from the integration tests.
Part of #487

tests: remove public-url config and add dex-oidc-config relation

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/1.19

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/1.20

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/1.22

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/1.18

---

.github/workflows/integrate.yaml

Temporary workaround for https://github.com/canonical/bundle-kubeflow/issues/1005.
The dev branch will be merged to `track/1.17` after merging also https://github.com/canonical/istio-operators/pull/526.

fix(ci): use charmcraft from latest/candidate in integration tests

---

charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl

Fix the CKF tag for istio-pilot dashboard. This tag should be lowercase and not upper case.
How to test this:
1. `tox -e cos-integration -- --keep-models`
2. Follow [guide](https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s#heading--deploy-the-cos-lite-bundle) to deploy COS.
3. Follow [guide](https://charmed-kubeflow.io/docs/integrate-with-cos) how integrate consume relation from COS.
fixes: #538

Fix tag istio-pilot dashboard tag

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml

chore(backport-1.17): Pin charmcraft channel to `3.x/stable`

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml

chore(backport-1.18): Pin charmcraft channel to `3.x/stable`

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml

chore(backport-1.19): Pin charmcraft channel to `3.x/stable`

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml

chore(backport-1.21): Pin charmcraft channel to `3.x/stable`

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml

chore(backport-1.22): Pin charmcraft channel to `3.x/stable`

---

charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl

Fix the CKF tag for istio-pilot dashboard. This tag should be lowercase and not upper case.
fixes: #538

chore(backport): Fix tag istio-pilot dashboard tag (#542)

---

.github/workflows/integrate.yaml
.gitignore
charms/istio-gateway/terraform/README.md
charms/istio-gateway/terraform/main.tf
charms/istio-gateway/terraform/outputs.tf
charms/istio-gateway/terraform/variables.tf
charms/istio-gateway/terraform/versions.tf
charms/istio-gateway/tox.ini
charms/istio-pilot/terraform/README.md
charms/istio-pilot/terraform/main.tf
charms/istio-pilot/terraform/outputs.tf
charms/istio-pilot/terraform/variables.tf
charms/istio-pilot/terraform/versions.tf
charms/istio-pilot/tox.ini

Ref: #552 and #530.
This PR creates a `terraform/` directory in each charm that hosts the Terraform module. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit).
To test the module:
- Clone the repository and switch to this branch.
- First run `tox -e tflint` to ensure that linting is correct
- Change to the `terraform/` directory and run `terraform init`.
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.

Feat: Add Terraform modules

---

.github/workflows/integrate.yaml
.gitignore
charms/istio-gateway/terraform/README.md
charms/istio-gateway/terraform/main.tf
charms/istio-gateway/terraform/outputs.tf
charms/istio-gateway/terraform/variables.tf
charms/istio-gateway/terraform/versions.tf
charms/istio-gateway/tox.ini
charms/istio-pilot/terraform/README.md
charms/istio-pilot/terraform/main.tf
charms/istio-pilot/terraform/outputs.tf
charms/istio-pilot/terraform/variables.tf
charms/istio-pilot/terraform/versions.tf
charms/istio-pilot/tox.ini

Ref: #552 and #530.
This PR is a backport that creates a `terraform/` directory in each charm that hosts the Terraform module. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit).
To test the module:
- Clone the repository and switch to this branch.
- First run `tox -e tflint` to ensure that linting is correct
- Change to the `terraform/` directory and run `terraform init`.
- Run `terraform apply -var "channel=1.22/stable" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.

(backport) Feat: Create Terraform module

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml
charms/istio-gateway/tests/unit/test_charm.py
tests/test_bundle.py

closes #496 
1. Using multipass, launch 2 VMs. The first VM will act as Node `1` and will contain the juju controller, the second VM will be act as Node `2`.
1.1 Launch first VM
```
multipass launch -c 4 -m 8Gb -d 60Gb -n juju-node-1
```
1.2 Launch second VM
```
multipass launch -c 2 -m 4Gb -d 30Gb -n other-vm
```
2. In each VM, install microk8s and enable add-ons:
```
sudo snap install microk8s --channel=1.29-strict/stable
sudo microk8s enable dns rbac hostpath-storage ingress metallb:10.64.140.43-10.64.140.49
```
3. Create a multi-node cluster by Joining Node `2` to Node `1`
3.1 In the first VM, run:
```
sudo microk8s add-node
```
you will get an output similar to:
```
From the node you wish to join to this cluster, run the following:
microk8s join …
```

feat: add configurable replicas and antiaffinity to gateway deployment for HA

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/data/egress-example.yaml
charms/istio-gateway/tests/unit/data/ingress-example.yaml
charms/istio-gateway/tests/unit/test_charm.py
tests/test_bundle.py

backports #553 to branch `track/1.22`

(backport) feat: add configurable replicas and antiaffinity to gateway deployment

---

charms/istio-pilot/terraform/outputs.tf

terraform: fix typo

---

charms/istio-gateway/requirements-fmt.txt
charms/istio-gateway/requirements-lint.txt
charms/istio-gateway/requirements-unit.txt
charms/istio-gateway/requirements.in
charms/istio-gateway/requirements.txt
charms/istio-gateway/tox.ini
charms/istio-pilot/requirements-fmt.txt
charms/istio-pilot/requirements-lint.txt
charms/istio-pilot/requirements-unit.txt
charms/istio-pilot/requirements.in
charms/istio-pilot/requirements.txt
charms/istio-pilot/tox.ini
requirements-fmt.txt
requirements-integration.txt
requirements-lint.txt
tox.ini

* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
Ref canonical/bundle-kubeflow#1177

chore: update python dependencies + pin pip

---

.github/workflows/integrate.yaml

Bump microk8s 1.29-1.31 according to https://github.com/kubeflow/community/issues/767#issuecomment-2593058929.
Ref canonical/bundle-kubeflow#1157

chore(ci): bump microk8s to 1.29-1.31

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
charms/istio-gateway/LICENSE
charms/istio-gateway/charmcraft.yaml
charms/istio-pilot/LICENSE
charms/istio-pilot/charmcraft.yaml

Closes #575
In order to be able to use the data-platform-workflows, specially to be compatible with charmcraft cache, the charmcraft.yaml files of all charms in this repository need to follow st124 notation.
NOTE this PR targets a dev branch as there is still pending work:
#579 
#577
It is expected to be merged in red due to parallel builds being problematic with charmcraft 3.3. This is expected to be fixed in the pending work linked above.

build: refactor charmcraft.yaml to use st124 notation

---

charms/istio-pilot/charmcraft.yaml

installs istioctl bin missed in https://github.com/canonical/charmed-kubeflow-solutions/pull/15
1. Clone repo and checkout branch `fix-build-install-istioctl`
2. Make sure you're using charmcraft `latest/stable`
3. Pack charms
```
cd charms/istio-pilot
charmcraft pack -v
cd charms/istio-gateway
charmcraft pack -v
```
4. Deploy charms and add relations
```
cd charms/istio-pilot
juju deploy ./istio-pilot_ubuntu@20.04-amd64.charm --trust
cd charms/istio-gateway
juju deploy ./istio-gateway_ubuntu@20.04-amd64.charm istio-ingressgateway --config kind=ingress --trust
juju relate istio-pilot istio-ingressgateway
```
Expected output:
charms go to active
```
juju status
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost …
```

fix: build istio-pilot install istioctl

---

charms/istio-pilot/README.md
charms/istio-pilot/src/charm.py

Originally, the TLS configuration that's done by passing a juju secret to istio-pilot was expected to last only a few versions of this charm, but as exposed in #536, this feature is needed until there is a solution that fits out users/customer needs better. Because of that, this commit removes the comments and warnings about deprecating this feature.

chore: remove deprecation warning for the TLS secret configuration

---

charms/istio-pilot/README.md
charms/istio-pilot/src/charm.py

Originally, the TLS configuration that's done by passing a juju secret to istio-pilot was expected to last only a few versions of this charm, but as exposed in #536, this feature is needed until there is a solution that fits out users/customer needs better. Because of that, this commit removes the comments and warnings about deprecating this feature.

(backport) chore: remove deprecation warning for the TLS secret configuration (#590)

---

charms/istio-gateway/config.yaml
charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/test_annotation_validators.py
charms/istio-gateway/tests/unit/test_charm.py

With the annotations configuration option, users will be able to add annotations to the Gateway Workload Service on demand.
Fixes #66
NOTE: all credits to @IbraAoad on the validation checks for the annotations. This PR is based on https://github.com/canonical/traefik-k8s-operator/pull/428.
---
1. Deploy `istio-pilot` (preferably from 1.24/stable)
2. Deploy `istio-gateway` from this PR and configure it as `ingress`:
```
juju deploy ./istio-gateway_ubuntu@20.04-amd64.charm istio-ingressgateway --config kind=ingress --trust
```
3. Check the `istio-ingressgateway-workload` does not contain any labels:
```
kubectl get svc -nistio-611 istio-ingressgateway-workload -oyaml
apiVersion: v1
kind: Service
metadata:
creationTimestamp: "2025-04-16T01:45:51Z"
labels:
app: istio-ingressgateway …
```

feat(gateway): add annotations configuration option for Service

---

charms/istio-gateway/charmcraft.yaml
charms/istio-gateway/config.yaml
charms/istio-gateway/constraints.txt
charms/istio-gateway/src/charm.py
charms/istio-gateway/src/manifest.yaml
charms/istio-gateway/tests/unit/test_annotation_validators.py
charms/istio-gateway/tests/unit/test_charm.py
charms/istio-pilot/charmcraft.yaml
charms/istio-pilot/constraints.txt

This PR is a backport of:
* feat(gateway): add annotations configuration option for Service (#611)
* fix(workaround): set constraints to setuptools-scm to avoid install loops (#618)

backport: fix for #66 and setuptools_scm constraints

---

requirements-integration.txt
tests/charms_dependencies.py
tests/test_bundle.py
tests/test_bundle_tls_provider.py

Move dependency charms deployed during tests to a separate file called
charms_dependencies.py. This enables programmatic access to them and
thus updating them centrally, probably with the use of `kfcicli`. This
uses the `CharmSpec` dataclass from chisme.
Ref canonical/bundle-kubeflow/issues/1256

refactor(tests): Move dependency charms to a separate file
