- charms/istio-ingressgateway/metadata.yaml
- charms/istio-pilot/metadata.yaml
Removes some old commented out code, fixes tags, and regularizes resources
> Cleanup charm metadata

- .github/workflows/test-microk8s.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/files/mesh
- charms/istio-pilot/reactive/charm.py
Also fixes a few issues to enable a successful deployment in CI.
> Add testing of deployment via github actions

- .github/workflows/check-formatting.yaml
- charms/istio-ingressgateway/reactive/charm.py
- charms/istio-pilot/reactive/charm.py
- pyproject.toml
Formats code with black and adds CI step to ensure it stays that way
> Add code lint check with github actions

- .github/workflows/publish-bundle.yaml
On commits or merges to master, publish bundle to charm store
> Publish master branch to edge channel in charm store

- .github/workflows/test-microk8s.yaml
> Wait longer for bookinfo to come up in CI

- .github/workflows/test-microk8s.yaml
- charms/istio-pilot/reactive/charm.py
It changed from a mapping to a list
Fixes #9
> Fix pod spec set v3 usage

- CODEOWNERS
> Adding more CODEOWNERS

- .github/workflows/publish-bundle.yaml
Publishes charms as well, and includes some extra bash goodness
> Better bundle publishing

- .github/workflows/publish-bundle.yaml
They were getting published to `~knkski`
> Publish charms to proper namespace

- charms/istio-pilot/reactive/charm.py
Ensures that filtering doesn't get skipped due to empty list
> Better route handling

- charms/istio-pilot/src/charm.py
According to schema they are optional
> Allow missing allowed headers values

- charms/istio-ingressgateway/requirements.txt
- charms/istio-ingressgateway/src/charm.py
- charms/istio-ingressgateway/test-requirements.txt
- charms/istio-ingressgateway/test/unit/test_charm.py
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/requirements.txt
- charms/istio-pilot/src/charm.py
- charms/istio-pilot/test-requirements.txt
- charms/istio-pilot/test/unit/test_charm.py
- Centralize all the logic in to one method
- Pin dependencies to pull correct libraries
- Add files to charmcraft.yaml
> Fix status handling and make the charms buildable

- charms/istio-gateway/metadata.yaml
- charms/istio-pilot/metadata.yaml
closes:https://github.com/canonical/bundle-kubeflow/issues/425
> add min-juju-version

- charms/istio-pilot/src/charm.py
Previously handle_ingress checked for errors by equality `(caught_error == SomeErrorType)`, which asserts that the caught_error is actually the class not an instance of the class. This is fixed here by changing to `isinstance(caught_error, SomeErrorType)`
> fix: istio-pilot error handling around gateway address

- .github/workflows/integration.yaml
Convert CI into a reusable workflow
> Updated CI

- charms/istio-pilot/tests/unit/conftest.py
- charms/istio-pilot/tests/unit/test_resources_handler.py
* New unit tests for istio-pilot charm `resources_handler.py` module.
* Added identifiers to parameterized tests to improve report readability.
> Add unit test coverage

- charms/istio-gateway/config.yaml
- charms/istio-gateway/src/charm.py
- charms/istio-gateway/src/manifest.yaml
- charms/istio-gateway/tests/unit/conftest.py
- charms/istio-gateway/tests/unit/test_charm.py
This is PR based on: https://github.com/canonical/istio-operators/pull/67
This PR allows exposing applications behind the Istio gateway via  Ingress Controller & rule
> Added ingress service type variable (ClusterIP or Loadbalancer)

- .github/workflows/integrate.yaml
- charms/istio-pilot/lib/charms/grafana_k8s/v0/grafana_dashboard.py
- charms/istio-pilot/lib/charms/observability_libs/v0/juju_topology.py
- charms/istio-pilot/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- charms/istio-pilot/metadata.yaml
- charms/istio-pilot/src/charm.py
- test-requirements.txt
- tests/test_cos_integration.py
- tox.ini
This PR adds the following:
* [feat: add grafana and prometheus for monitoring](https://github.com/canonical/istio-operators/commit/94e8d169b8d452540968c396521a5afda660c68a)
* [test: add integration test for prometheus, grafana and istio-pilot](https://github.com/canonical/istio-operators/commit/044349e1e39f07c7f9e5bc227c8780178d76b0b9)
NOTE: integration tests may fail due to issues with the current CI, #131 aims at fixing the majority of them.
> feat: integrate istio-pilot with prometheus and grafana

- charms/istio-pilot/lib/charms/grafana_k8s/v0/grafana_dashboard.py
- charms/istio-pilot/lib/charms/observability_libs/v0/juju_topology.py
- charms/istio-pilot/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Library charms.prometheus_k8s.v0.prometheus_scrape updated to version 0.30.
Library charms.observability_libs.v0.juju_topology updated to version 0.6.
Library charms.grafana_k8s.v0.grafana_dashboard updated to version 0.24.
> bump all charm libs to latest version

- charms/istio-pilot/README.md
Improves instructions around recovering from failing upgrades, particularly for when users are stuck in an Error state.
> docs: add detail to istio-pilot upgrade recovery instructions

- charms/istio-gateway/src/manifest.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
> build: backport version bump istio 1.11->1.16 in gateway files to track/1.16

- charms/istio-gateway/src/manifest.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
> fix: add missing volume mounts and volumes to istio-gateway's gateway

- charms/istio-pilot/tests/unit/test_gateway_info.py
Adds minimal unit tests for current version of the library.
> test: add gateway-info library unit tests to expand coverage

- .github/workflows/publish.yaml
- .github/workflows/release.yaml
Bump to latest version to fix issues.
> ci: bump charming-actions 2.2.2 -> 2.2.5

- charms/istio-pilot/src/charm.py
Use the latest version of gateway-info library. 
This PR should be merged after #237
> refactor: use refactored gateway-info in handle_gateway_info event handler

- charms/istio-pilot/src/charm.py
- charms/istio-pilot/src/manifests/auth_filter.yaml.j2
- charms/istio-pilot/tests/unit/test_charm.py
This adds:
* handling for multiple non-fatal errors
* e2e-style unit tests using harness
* bugfixes for things found during unit testing
> feat: finish the istio-pilot main reconcile handler (for event handling rewrite)

- charms/istio-gateway/config.yaml
- charms/istio-gateway/src/charm.py
- charms/istio-gateway/src/manifest.yaml
More details in: https://github.com/canonical/istio-operators/issues/322
- Added proxy-image config option.
- Updated manifest template with placeholder for proxy image.
- Modified charm code to render manifest with proxy image from configuration.
For complete testing refer to https://github.com/canonical/istio-operators/issues/322
> feat: configurable images for istio-gateway

- tools/get-images.sh
Refer to this issue for more details: https://github.com/canonical/bundle-kubeflow/issues/679
Summary of changes:
- Updated get images script to dynamically extract Istio images
> fix: updated get-images script

- .github/workflows/integrate.yaml
- requirements-integration.in
- requirements-integration.txt
ci: update juju to 3.1 and pin python-libjuju to <4.0
> ci: update juju to 3.1

- charms/istio-gateway/metadata.yaml
- charms/istio-pilot/metadata.yaml
> Discourse docs

- .github/workflows/integrate.yaml
- charms/istio-gateway/config.yaml
- charms/istio-gateway/src/charm.py
- charms/istio-gateway/src/manifest.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/src/charm.py
- charms/istio-pilot/tests/unit/test_charm.py
- tools/get-images.sh
Cherry-picking commits to ensure images are configurable for airgapped environment.
More details are in https://github.com/canonical/istio-operators/issues/332
Only the following commits were merged to support image configuration in airgapped environment:
- 3974636
- 293f90a
- bed0151
> Kf 4432 fix cherry pick images config

- charms/istio-pilot/src/charm.py
- charms/istio-pilot/tests/unit/test_charm.py
* fix: set charm to waitingStatus if missing ingress auth data
* Add unit tests
> fix(cherry-pick): set charm to waitingStatus if missing ingress auth data (#342)

- charms/istio-pilot/metadata.yaml
- tests/test_bundle.py
Merge the commits introduced by #389 and #388 into `track/1.17`
> Merge dev branch into track/1.17

- charms/istio-gateway/config.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/src/istioctl.py
- charms/istio-pilot/tests/unit/test_charm.py
- charms/istio-pilot/tests/unit/test_istioctl.py
- tests/test_bundle.py
This commit adds support for istio operators 1.19.10.
Part of #413
> feat: add support for istio 1.19.10

- charms/istio-gateway/config.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/src/istioctl.py
- charms/istio-pilot/tests/unit/test_charm.py
- charms/istio-pilot/tests/unit/test_istioctl.py
- tests/test_bundle.py
This commit adds support for istio operators 1.21.2.
Part of #413
> feat: add support for istio 1.21.2

- charms/istio-gateway/config.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/src/istioctl.py
- charms/istio-pilot/tests/unit/test_charm.py
- charms/istio-pilot/tests/unit/test_istioctl.py
- tests/test_bundle.py
This commit adds support for istio operators 1.22.0.
Part of #413
> feat: add support for istio 1.22.0

- charms/istio-gateway/config.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/src/istioctl.py
- charms/istio-pilot/tests/unit/test_charm.py
- charms/istio-pilot/tests/unit/test_istioctl.py
- tests/test_bundle.py
This commit adds support for istio operators 1.18.7.
Part of #413
> feat: add support for istio 1.18.7

- charms/istio-gateway/requirements-unit.txt
- charms/istio-gateway/requirements.txt
- charms/istio-pilot/requirements-unit.txt
- charms/istio-pilot/requirements.txt
Part of canonical/bundle-kubeflow#868
> build: bump ops to latest possible version

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14 in track/1.18

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14 in track/1.22

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14  in main

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14 in track/1.19

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14  in track/1.20

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14 in track/1.21

- charms/istio-pilot/lib/charms/observability_libs/v0/cert_handler.py
> build: bump cert_handler 13 -> 14  in track/1.17

- charms/istio-gateway/requirements-unit.txt
- charms/istio-gateway/requirements.txt
- charms/istio-pilot/README.md
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/requirements-unit.txt
- charms/istio-pilot/requirements.in
- charms/istio-pilot/requirements.txt
* jinja update
* Remove tls libs from charmcraft in istio-pilot and move them to requirements
> Fix istio CI (#476)

- charms/istio-pilot/do-not-merge-message.txt
- charms/istio-pilot/lib/charms/grafana_k8s/v0/grafana_dashboard.py
- charms/istio-pilot/lib/charms/observability_libs/v1/cert_handler.py
- charms/istio-pilot/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- charms/istio-pilot/lib/charms/tls_certificates_interface/v3/tls_certificates.py
* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file. This spotted a new major version for tls-certificates library for which there is a PR in progress https://github.com/canonical/istio-operators/pull/568.
Ref canonical/bundle-kubeflow#1184
Note that this is blocked on #567
> chore: bump libraries

- charms/istio-gateway/config.yaml
- charms/istio-gateway/tests/unit/data/egress-example.yaml
- charms/istio-gateway/tests/unit/data/ingress-example.yaml
- charms/istio-pilot/charmcraft.yaml
- charms/istio-pilot/config.yaml
- charms/istio-pilot/src/grafana_dashboards/istio_control_plane.json.tmpl
- tests/test_bundle.py
This commit adds support for istio operators 1.23.4.
Please note this PR is targeting track/1.23
> feat: add support for istio 1.23

- .github/workflows/ci.yaml
- .github/workflows/promote.yaml
> chore(ci): bump GH runners to ubuntu-24.04

- charms/istio-pilot/src/charm.py
In a previous version of the istio-pilot charm, the extra_sans_dns argument of the CertHandler was not set, meaning that the library will always use the FQDN of the Istio Ingress Service as the value for the SANS in the CSR. While this is an implementation detail of the CertHandler library, it was impossible for users to set it correctly using their desired DNS names. This commit ensures the SANS is pointing to the csr-domain-name (if configured) or the service's IP address.
Fixes #557
---
1. Deploy `istio-gateway` as kind=ingress (preferably from 1.24/stable)
2. Deploy `istio-pilot` from this PR
3. Configure `istio=pilot`'s `csr-domain-name`
```
juju config istio-pilot csr-domain-name="kubeflow-aaabbbccc.region.cloudapp.mycloud.com"
```
4. Deploy the `manual-tls-certificates` operator …
> fix(tls): use cert_subject in the sans and cert_subject fields

- charms/istio-gateway/terraform/versions.tf
- charms/istio-pilot/terraform/versions.tf
Updating juju provider requirement to >=0.14.0
> [KF-7255] Update Juju provider

- charms/istio-pilot/src/charm.py
In a previous version of the istio-pilot charm, the sans argument of the CertHandler was not set, meaning that the library will always use the FQDN of the Istio Ingress Service as the value for the SANS in the CSR. While this is an implementation detail of the CertHandler library, it was impossible for users to set it correctly using their desired DNS names. This commit ensures the SANS is pointing to the csr-domain-name (if configured) or the service's IP address.
Fixes #557 in track/1.24
> fix(tls): use cert_subject in the sans and cert_subject fields (#614)

- charms/istio-gateway/terraform/variables.tf
- charms/istio-gateway/terraform/versions.tf
- charms/istio-pilot/terraform/variables.tf
- charms/istio-pilot/terraform/versions.tf
Cutting new release for branch track/1.24
> [KF-7254] Release 1.10

- charms/istio-gateway/terraform/variables.tf
- charms/istio-pilot/terraform/variables.tf
> [KF-7268] chore: pin channel to latest/edge

- tests/test_bundle.py
- tests/test_bundle_tls_provider.py
Pin charms-dependencies according to 1.10/stable bundle.
Close https://warthogs.atlassian.net/browse/KF-7233
> chore(tests): Pin charms-dependencies
